### ISSUE TITLE
Type issue in ini_setting?

### ISSUE THREAD

**Issue by cnunemaker** [voroniys/puppet_compat#1]
The ini_setting resource seems to always erroneously attempt to remediate when the value is an integer.
For example, assume we have the following simple ini_setting with an integer value:
```ruby
file 'temp' do
  path '/tmp/test.ini'
end
ini_setting 'baz' do
  path '/tmp/test.ini'
  section 'bar'
  setting 'foo'
  value '1'
end
```
Running it the first time works fine since the value is unset. The issue occurs on the second and subsequent runs:
```
Recipe: foo::default
  * file[temp] action create (up to date)
  * ini_setting[baz] action ensure
    - Set 'foo' in section 'bar' of '/tmp/test.ini' file to '1', was '1'
```
'1' should equal to '1' unless they are not of the same type somehow. After editing some logging statements into the code just prior to [this line](https://github.com/voroniys/puppet_compat/blob/master/libraries/inifile_provider.rb#L34), the following is output:
```
Converging 2 resources
[2018-09-11T13:08:47-05:00] DEBUG: Converging node rhel73-chef
[2018-09-11T13:08:47-05:00] DEBUG: Converging node rhel73-chef
Recipe: foo::default
  * file[temp] action create[2018-09-11T13:08:47-05:00] INFO: Processing file[temp] action create (foo::default line 1)
[2018-09-11T13:08:47-05:00] INFO: Processing file[temp] action create (foo::default line 1) (up to date)
  * ini_setting[baz] action ensure[2018-09-11T13:08:47-05:00] INFO: Processing ini_setting[baz] action ensure (foo::default line 4)                                                                                                         │[root@rhel73-chef libraries]#
[2018-09-11T13:08:47-05:00] INFO: Processing ini_setting[baz] action ensure (foo::default line 4)
[2018-09-11T13:08:47-05:00] DEBUG: ini[section][setting] is a Integer
[2018-09-11T13:08:47-05:00] DEBUG: ini[section][setting] is a Integer
[2018-09-11T13:08:47-05:00] DEBUG: value is a String
[2018-09-11T13:08:47-05:00] DEBUG: value is a String

    - Set 'foo' in section 'bar' of '/tmp/test.ini' file to '1', was '1'
```
This clearly shows a comparison is occurring between an Integer and a String.
Forcing ini[section][setting] into a String via to_s seems to resolve the issue, but I am unsure if this is the most appropriate fix.

Please advise. Thank you.

**Comment by voroniys** [comment]
Thank a lot for reporting the issue. It is fixed now.

**Comment by cnunemaker** [comment]
Thank you for fixing this issue. I can confirm that my issue is now fixed.
